// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjpnvexhuocbeirswpoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qcG52ZXhodW9jYmVpcnN3cG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzczMTQsImV4cCI6MjA3MjI1MzMxNH0._2hsDN4-Y2HbZc-YG6Fyj-pO7DGdwsJ7LpmwOwd5xFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
